### ISSUE TITLE
Verify matching results against Yale ground-truth datasets

### ISSUE THREAD

**Issue by timathom** [yale-datachemist/entity-resolution#30]
Once embeddings have been generated, test them using the following two datasets:
* [Yale catalog disambiguated names](https://github.com/yale-datachemist/entity-resolution/blob/main/data/Yale_catalog_disambiguated_names.csv)
* [Yale catalog names without dates](https://github.com/yale-datachemist/entity-resolution/blob/main/data/Yale_catalog_names_without_dates.csv)

**Comment by GavinMendelGleason** [comment]
We obtained the following results against the Yale ground truth

```
total: 2599                                          
relevant: 172                                          
positive: 143                                        
recall: 0.06617929973066564                       
precision: 0.8313953488372093
```
