### ISSUE TITLE
VectorLink load command doesn't build index

### ISSUE THREAD

**Issue by timathom** [yale-datachemist/entity-resolution#44]
The [README](https://github.com/yale-datachemist/entity-resolution?tab=readme-ov-file#run-indexing) lists the `load` command, with the `--build-index` switch. However, I just tested with a small dataset of 326 records, and the index never seems to get built. It seems to hang after the embeddings have been retrieved.

[Test file is here](https://github.com/yale-datachemist/entity-resolution/blob/main/data/test/authority_ops_test.json) (326 records that all contain the word "Tolkien").

Command:
```
vectorlink load -k $OPENAI_KEY -c fakecommit --domain loc -d /home/DataChemist/data/vector_storage -i authority_ops_test.json --size 8738134 --build-index true -m small3 -q > error_test.txt
```

Output:
``` 
retrieved embeddings
saved embeddings
indexed 326
Concatenating to vector store
byte_size: 2002944
vector_byte_size: 6144
minute passed. budget now 951457
minute passed. budget now 974500
minute passed. budget now 993996
minute passed. budget now 1000000
```

The `loc.vecs` file does get created, but it's empty.

**Comment by timathom** [comment]
I manually copied the vectors file from `vector_storage/.staging/loc/vectors` to `vector_storage/loc.vecs`. Then I ran the index command:
```
vectorlink index --directory /home/DataChemist/data/vector_storage --domain loc --commit pq8-take-1 --key fake -q > error_test_index.txt
```
But when I try a search (e.g., `curl 'http://localhost:8080?string=Pippin'`--the word "Pippin" appears in exactly two records) the results seem basically random. First result is [http://id.loc.gov/rwo/agents/no00086546](https://id.loc.gov/authorities/names/no00086546.html), with a distance of 0.4627354. "Pippin" doesn't appear in this record.

**Comment by timathom** [comment]
@GavinMendelGleason @matko, I've added a [second test file](https://github.com/yale-datachemist/entity-resolution/blob/main/data/test/marc_ops_test.json) with some corresponding matches from the Yale data.

**Comment by matko** [comment]
I updated vectorlink and the instructions in the README to point to a version where this issue has been resolved.
