### ISSUE TITLE
handler.rs missing in vectorlink-quantizer?

### ISSUE THREAD

**Issue by timathom** [yale-datachemist/entity-resolution#48]
I'm trying to build VectorLink from the `generic_storage` branch and getting an error because of the `mod handler` in [vectorlink-quantizer/main.rs](https://github.com/terminusdb-hub/vectorlink/tree/generic_storage/vectorlink-quantizer/src/main.rs). Is there a missing `handler.rs` file?

**Comment by matko** [comment]
This could very well be a missing file, but I don't think you need this particular project to build. All you really need to build is vectorlink itself.

How are you trying to run this build?

**Comment by timathom** [comment]
@matko, thanks, I was just testing to see whether there was a difference in running the app directly (e.g., `vectorlink load ...`) vs. using Nix, but it seems the results are the same (i.e., not working as expected).

**Comment by matko** [comment]
Closing this here, as it should not be relevant to getting entity resolution working.
