### ISSUE TITLE
Yale Project Redux

### ISSUE THREAD

**Issue by timathom** [yale-datachemist/entity-resolution#52]
@GavinMendelGleason, @matko, here's a summary from today's meeting:
- [x] Address #44
- [x] Address #42 
- [x] Investigate which embedding model is being used by `vectorlink search-server`. Is it the same as the model specified for load/index (i.e., `text-embedding-3-small`)?
- [x] Review [README](https://github.com/yale-datachemist/entity-resolution/blob/main/README.md) and ensure commands are up to date (e.g., remove `--size` param).

Two small files are available for testing:
1. Library of Congress data ([authority_ops_test.json](https://github.com/yale-datachemist/entity-resolution/blob/main/data/test/authority_ops_test.json))
2. Matching names from Yale data ([marc_ops_test.json](https://github.com/yale-datachemist/entity-resolution/blob/main/data/test/marc_ops_test.json)). _Includes fuzzy (low probability) matches._

As long as the issues are resolved and the test results are reasonable (if not optimal), I don't think we need to process the complete datasets at this point. I can work on that independently.

**Comment by matko** [comment]
The search server will always use the model that was used to build the index. It'll get this from the metadata that is stored along with said index.

When an embedding string exceeds the maximum length allowed, it will be truncated. it will not be chunked. We'll simply lose information in that case.

**Comment by matko** [comment]
With the version that is now documented in the readme, we were able to index both test files and start a search server for them.
